version: '3'

services:
  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql_volume:
    driver: local
